<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Logout</name>
   <tag></tag>
   <elementGuidId>1508369e-82af-4de7-8ac9-2e188ac3cdaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.css-queiy2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-root']/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>NavigationItem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-queiy2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[2]/div[@class=&quot;css-a1uz4q-LayoutContainer&quot;]/div[@class=&quot;css-58k9v9-NavigationContainer&quot;]/div[@class=&quot;css-1qjvlxm-ContainerNavigationMask&quot;]/div[@class=&quot;css-1yxtf1y-ContentNavigationWrapper&quot;]/div[@class=&quot;css-1y540l9-ContainerNavigationPrimitiveBase&quot;]/div[@class=&quot;css-9uaqau-ScrollProvider&quot;]/div[@class=&quot;css-hwlzh1-ScrollableTransitionGroup&quot;]/div[@class=&quot;css-xdwmn0&quot;]/div[@class=&quot;css-1hpn4bw&quot;]/div[@class=&quot;css-1tw9lwf&quot;]/div[@class=&quot;css-7xjigh&quot;]/button[@class=&quot;css-queiy2&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New version'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shortcuts'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/button</value>
   </webElementXpaths>
</WebElementEntity>
