<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>5ae37c71-b0ee-4795-bd20-174ea6ac1fe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>g.AvatarImage__ShapeGroup-sc-1hf6c4m-0.lcCoJI > circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>64</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>64</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>64</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[2]/div[@class=&quot;css-a1uz4q-LayoutContainer&quot;]/div[@class=&quot;css-58k9v9-NavigationContainer&quot;]/div[@class=&quot;css-1qjvlxm-ContainerNavigationMask&quot;]/div[1]/div[@class=&quot;css-zjbnrj&quot;]/div[@class=&quot;css-1kacc6j-SecondaryItemsList&quot;]/div[@class=&quot;css-2rlxtj&quot;]/div[@class=&quot;css-7xjigh&quot;]/div[1]/div[@class=&quot;css-1baulvz&quot;]/span[@class=&quot;css-etb259&quot;]/a[1]/div[1]/span[@class=&quot;styledCache__StyledSpan-zohhd2-3 cwXEzS&quot;]/svg[1]/g[@class=&quot;AvatarImage__ShapeGroup-sc-1hf6c4m-0 lcCoJI&quot;]/circle[1]</value>
   </webElementProperties>
</WebElementEntity>
