<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Microsoft_Sync_Button</name>
   <tag></tag>
   <elementGuidId>bf9ab647-1cac-4972-930f-012982d0b405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.sync-links.mb_16.mt_20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-root']/div[2]/div[2]/div[2]/a[2]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://login.microsoftonline.com/common/oauth2/v2.0/authorize?scope=https://graph.microsoft.com/User.Read%20Contacts.Read%20Mail.Read%20Mail.Send%20People.Read%20offline_access&amp;access_type=offline&amp;redirect_uri=https://api-dev.onmyradar.io/api/oauth/microsoft&amp;response_type=code&amp;client_id=0d372173-3244-465a-8a36-a943868e89b0&amp;prompt=consent&amp;state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6ImUyZS50ZXN0LmNvbnRhY3RzLmxpc3QiLCJlbWFpbCI6ImUyZS50ZXN0LmNvbnRhY3RzLmxpc3RAb25teXJhZGFyLmNvbSIsInVzZXJuYW1lIjoiZTJlLnRlc3QuY29udGFjdHMubGlzdCIsImlkIjoyMDQsInVpZCI6ImF1dGgwfDYwMDhiNjAyZmZjYmUyMDA2YTg4MWRiMyJ9.Noiq4HaVwNVesmTPyvHZhTg5z1eSvbIACVBMSIVxk_M</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sync-links mb_16 mt_20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sync Microsoft account</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[2]/div[@class=&quot;container container_settings px_0&quot;]/div[@class=&quot;mt_56&quot;]/a[@class=&quot;sync-links mb_16 mt_20&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div[2]/div[2]/div[2]/a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sync Microsoft account')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sync Google account'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can sync as many accounts as you want'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sync Twitter Account'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sync Microsoft account']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize?scope=https://graph.microsoft.com/User.Read%20Contacts.Read%20Mail.Read%20Mail.Send%20People.Read%20offline_access&amp;access_type=offline&amp;redirect_uri=https://api-dev.onmyradar.io/api/oauth/microsoft&amp;response_type=code&amp;client_id=0d372173-3244-465a-8a36-a943868e89b0&amp;prompt=consent&amp;state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6ImUyZS50ZXN0LmNvbnRhY3RzLmxpc3QiLCJlbWFpbCI6ImUyZS50ZXN0LmNvbnRhY3RzLmxpc3RAb25teXJhZGFyLmNvbSIsInVzZXJuYW1lIjoiZTJlLnRlc3QuY29udGFjdHMubGlzdCIsImlkIjoyMDQsInVpZCI6ImF1dGgwfDYwMDhiNjAyZmZjYmUyMDA2YTg4MWRiMyJ9.Noiq4HaVwNVesmTPyvHZhTg5z1eSvbIACVBMSIVxk_M')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
   </webElementXpaths>
</WebElementEntity>
