<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__asa</name>
   <tag></tag>
   <elementGuidId>5a253b51-9870-42e5-a40a-430c50caf42d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.T-I.J-J5-Ji.nX.T-I-ax7.T-I-Js-Gs.mA.T-I-JW.T-I-JO.T-I-Zf-aw2 > div.asa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':4']/div[2]/div/div/div[2]/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>asa</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:4&quot;)/div[@class=&quot;G-atb D E&quot;]/div[@class=&quot;iH bzn&quot;]/div[@class=&quot;G-tF&quot;]/div[@class=&quot;G-Ni G-aE J-J5-Ji&quot;]/div[@class=&quot;T-I J-J5-Ji nX T-I-ax7 T-I-Js-Gs mA T-I-JW T-I-JO T-I-Zf-aw2&quot;]/div[@class=&quot;asa&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':4']/div[2]/div/div/div[2]/div[3]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más'])[3]/preceding::div[21]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[3]/div</value>
   </webElementXpaths>
</WebElementEntity>
