name: CI
on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '7.7.2'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/OMR-development-test" -apiKey=${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'
